Algoritmo "REPITA_MENU"

Var
  opcao: inteiro

Inicio
Repita
      Escreval("1 - Dizer olá! ")
      Escreval("2 - Dizer oi! ")
      Escreval("0 - Sair do programa")
      Leia(opcao)
      Se (opcao = 1) entao
         Escreval("Olá!")
      Fimse
      
      Se (opcao = 2) entao
         Escreval("Oi!")
      Fimse
Ate (opcao = 0)
Escreval("Saiu do repita")
      
      
      

Fimalgoritmo